//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/_Project/InputActions/StageMindActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace StageMind
{
    public partial class StageMindActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }

        public StageMindActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""StageMindActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""a1b2c3d4-e5f6-7890-abcd-ef1234567890"",
            ""actions"": [
                {
                    ""name"": ""AdvanceSlide"",
                    ""type"": ""Button"",
                    ""id"": ""f1a2b3c4-d5e6-7890-abcd-111111111111"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PreviousSlide"",
                    ""type"": ""Button"",
                    ""id"": ""f1a2b3c4-d5e6-7890-abcd-222222222222"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""f1a2b3c4-d5e6-7890-abcd-333333333333"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b1a2b3c4-d5e6-7890-abcd-111111111111"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AdvanceSlide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1a2b3c4-d5e6-7890-abcd-222222222222"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousSlide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1a2b3c4-d5e6-7890-abcd-333333333333"",
                    ""path"": ""<XRController>{LeftHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""a2b3c4d5-e6f7-8901-bcde-ef2345678901"",
            ""actions"": [
                {
                    ""name"": ""UIPoint"",
                    ""type"": ""Value"",
                    ""id"": ""f2a3b4c5-d6e7-8901-bcde-111111111111"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UIClick"",
                    ""type"": ""Button"",
                    ""id"": ""f2a3b4c5-d6e7-8901-bcde-222222222222"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b2a3b4c5-d6e7-8901-bcde-111111111111"",
                    ""path"": ""<XRController>{RightHand}/pointerPosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIPoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2a3b4c5-d6e7-8901-bcde-222222222222"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Haptics"",
            ""id"": ""a3b4c5d6-e7f8-9012-cdef-ef3456789012"",
            ""actions"": [
                {
                    ""name"": ""HapticRight"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f3a4b5c6-d7e8-9012-cdef-111111111111"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HapticLeft"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f3a4b5c6-d7e8-9012-cdef-222222222222"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b3a4b5c6-d7e8-9012-cdef-111111111111"",
                    ""path"": ""<XRController>{RightHand}/{Haptic}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HapticRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3a4b5c6-d7e8-9012-cdef-222222222222"",
                    ""path"": ""<XRController>{LeftHand}/{Haptic}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HapticLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
            m_Gameplay_AdvanceSlide = m_Gameplay.FindAction("AdvanceSlide", throwIfNotFound: true);
            m_Gameplay_PreviousSlide = m_Gameplay.FindAction("PreviousSlide", throwIfNotFound: true);
            m_Gameplay_PauseMenu = m_Gameplay.FindAction("PauseMenu", throwIfNotFound: true);

            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_UIPoint = m_UI.FindAction("UIPoint", throwIfNotFound: true);
            m_UI_UIClick = m_UI.FindAction("UIClick", throwIfNotFound: true);

            m_Haptics = asset.FindActionMap("Haptics", throwIfNotFound: true);
            m_Haptics_HapticRight = m_Haptics.FindAction("HapticRight", throwIfNotFound: true);
            m_Haptics_HapticLeft = m_Haptics.FindAction("HapticLeft", throwIfNotFound: true);
        }

        ~StageMindActions()
        {
            UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, StageMindActions.Gameplay.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, StageMindActions.UI.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Haptics.enabled, "This will cause a leak and performance issues, StageMindActions.Haptics.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action) => asset.Contains(action);

        public IEnumerator<InputAction> GetEnumerator() => asset.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        public void Enable() => asset.Enable();

        public void Disable() => asset.Disable();

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Gameplay
        private readonly InputActionMap m_Gameplay;
        private readonly InputAction m_Gameplay_AdvanceSlide;
        private readonly InputAction m_Gameplay_PreviousSlide;
        private readonly InputAction m_Gameplay_PauseMenu;

        public struct GameplayActions
        {
            private StageMindActions m_Wrapper;

            public GameplayActions(StageMindActions wrapper) { m_Wrapper = wrapper; }

            public InputAction AdvanceSlide => m_Wrapper.m_Gameplay_AdvanceSlide;
            public InputAction PreviousSlide => m_Wrapper.m_Gameplay_PreviousSlide;
            public InputAction PauseMenu => m_Wrapper.m_Gameplay_PauseMenu;

            public InputActionMap Get() => m_Wrapper.m_Gameplay;
            public void Enable() => Get().Enable();
            public void Disable() => Get().Disable();
            public bool enabled => Get().enabled;

            public static implicit operator InputActionMap(GameplayActions set) => set.Get();
        }

        public GameplayActions Gameplay => new GameplayActions(this);

        // UI
        private readonly InputActionMap m_UI;
        private readonly InputAction m_UI_UIPoint;
        private readonly InputAction m_UI_UIClick;

        public struct UIActions
        {
            private StageMindActions m_Wrapper;

            public UIActions(StageMindActions wrapper) { m_Wrapper = wrapper; }

            public InputAction UIPoint => m_Wrapper.m_UI_UIPoint;
            public InputAction UIClick => m_Wrapper.m_UI_UIClick;

            public InputActionMap Get() => m_Wrapper.m_UI;
            public void Enable() => Get().Enable();
            public void Disable() => Get().Disable();
            public bool enabled => Get().enabled;

            public static implicit operator InputActionMap(UIActions set) => set.Get();
        }

        public UIActions UI => new UIActions(this);

        // Haptics
        private readonly InputActionMap m_Haptics;
        private readonly InputAction m_Haptics_HapticRight;
        private readonly InputAction m_Haptics_HapticLeft;

        public struct HapticsActions
        {
            private StageMindActions m_Wrapper;

            public HapticsActions(StageMindActions wrapper) { m_Wrapper = wrapper; }

            public InputAction HapticRight => m_Wrapper.m_Haptics_HapticRight;
            public InputAction HapticLeft => m_Wrapper.m_Haptics_HapticLeft;

            public InputActionMap Get() => m_Wrapper.m_Haptics;
            public void Enable() => Get().Enable();
            public void Disable() => Get().Disable();
            public bool enabled => Get().enabled;

            public static implicit operator InputActionMap(HapticsActions set) => set.Get();
        }

        public HapticsActions Haptics => new HapticsActions(this);
    }
}
